### ISSUE TITLE
运行evaluate_model.py时出错？

### ISSUE THREAD

**Issue by hongsheng-Z** [XLechter/Rank-PointRetrieval#1]
作者您好，在看完您的论文后我想是这复现一下这个代码，但是当我在运行evaluate_model.py时出现了错误，具体如下：
我在终端运行：`python evaluate_model.py --model pointnetvlad --dataset_prefix oxford --with_reg --reg 'vc'`
然后一直卡在：
<img width="1432" alt="截屏2023-04-22 17 49 06" src="https://user-images.githubusercontent.com/37135497/233776942-cdb5ab38-a4ae-4fef-bae6-88d9a19ba9fb.png">

**Comment by XLechter** [comment]
如果没报错的话应该是机器本身cpu资源不足的问题  试试cpu_using调小一些看看还会不会卡住  这个计算本身也比较慢

**Comment by hongsheng-Z** [comment]
> 

您好，请问您这个evaluation的过程大概花了多久，我服务器开了8核，在business上已经两天多了还是没出结果。

**Comment by XLechter** [comment]
> > 
> 
> 您好，请问您这个evaluation的过程大概花了多久，我服务器开了8核，在business上已经两天多了还是没出结果。

oxford数据集的话是比较久的  如果进程还在运行的话说明还没有reranking结束  之前运行是用的32核的cpu

你可以跑下另外几个数据集  数据量比较小是会比较快的

**Comment by hongsheng-Z** [comment]
好的，谢谢。但是我在train的时候，好像没有发现probability- based loss这个模块呀

**Comment by XLechter** [comment]
> 好的，谢谢。但是我在train的时候，好像没有发现probability- based loss这个模块呀

没记错的话当时我应该是命名成triplet_ranking_loss了

**Comment by hongsheng-Z** [comment]
好的 谢谢大佬呀
